version: '3.8'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    ports: 
      - "443:443"
    restart: on-failure
    volumes: 
      - wp:/usr/share/nginx/html/
    networks: 
      - inception
    depends_on: 
      - wordpress
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    restart: on-failure
    expose:
      - "9000"
    volumes: 
      - wp:/var/www/wordpress
    depends_on: 
      - mariadb
    networks: 
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    expose:
      - "3306"
    volumes: 
      - /home/gponcele/data/mariadb:/var/lib/mysql/
    restart: unless-stopped
    networks: 
      - inception

volumes:
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gponcele/data/wordpress'

networks:
  inception:
    driver: bridge
