version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    ports: 
      - "443:443"
    restart: on-failure
    volumes: 
      - wordpress_data:/usr/share/nginx/html/
    networks: 
      - inception
    depends_on: 
      - wordpress
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    restart: on-failure
    volumes: 
      - wordpress_data:/var/www/wordpress
    depends_on: 
      - mariadb
    networks: 
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes: 
      - /home/shukk/data/mariadb:/var/lib/mysql/
    restart: on-failure
    networks: 
      - inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/shukk/data/wordpress'

networks:
  inception:
    driver: bridge
